on:
  push:
    tags:
      - 'sz/*/db/*'

jobs:
  rename:
    name: Commit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run git tag action
        run: |
          echo "running action on tag: ${{ github.ref }}"
          [[ "${{ github.ref_name }}" =~ ^sz/(.*)/db/(.*)$ ]]
          DB_NAME="${BASH_REMATCH[1]}"
          DB_SZ_VERSION="${BASH_REMATCH[2]}"

          echo "DB_NAME=$DB_NAME"
          echo "DB_SZ_VERSION=$DB_SZ_VERSION"

          IMAGE_BASE="$DB_NAME-db:$DB_SZ_VERSION"
          echo "OK_IMAGE=${{ env.ACR }}/mpsv/maruska/images/sz/${IMAGE_BASE}"
          echo "MPSV_IMAGE=${{ env.MPSV_ACR }}/mpsv/maruska/images/sz/${IMAGE_BASE}"