on: workflow_dispatch

jobs:
  rename:
    name: Commit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename tags
        run: |
          git tag -l
          for tag in $(git tag -l); do
            echo "Processing tag: $tag"
          done