on: workflow_dispatch

jobs:
  rename:
    name: Rename
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Rename tags
        shell: bash
        run: |
          echo "*************BEFORE*************"
          git tag -l

          for tag in $(git tag -l); do
            echo "Processing tag: $tag"

            if [[ "$tag" =~ ^(.*)-([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
              APP_NAME_FULL="${BASH_REMATCH[1]}"
              APP_VERSION="${BASH_REMATCH[2]}"
              
              TYPE=""
              APP_NAME=""
              if [[ "$APP_NAME_FULL" =~ ^(.*)-fe$ ]]; then
                APP_NAME="${BASH_REMATCH[1]}"
                TYPE=fe
              else
                APP_NAME="$APP_NAME_FULL"
                TYPE=be
              fi;
              
              echo "[debug] taging $APP_NAME_FULL-$APP_VERSION to release/$APP_NAME/$TYPE/$APP_VERSION"
              git tag release/$APP_NAME/$TYPE/$APP_VERSION $APP_NAME_FULL-$APP_VERSION
              
              # git tag release/datsch/1.0.5 datsch-1.0.5
              # git push origin release/datsch/1.0.5 :datsch-1.0.5
            fi;
          done

          echo "*************AFTER*************"
          git tag -l