on: workflow_dispatch

jobs:
  rename:
    name: Commit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rename tags
        shell: bash
        run: |
          git tag -l
          for tag in $(git tag -l); do
            echo "Processing tag: $tag"
          done