on: workflow_dispatch

jobs:
  rename:
    name: Rename
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Rename tags
        shell: bash
        run: |
          for tag in $(git tag -l); do
            echo "Processing tag: $tag"
            git tag release/datsch/1.0.0 datsch-1.0.0
            git push origin release/datsch/1.0.0 :datsch-1.0.0
          done